### ISSUE TITLE
大佬，应你的要求我做了一个，但是并未测试，我没用过v2ray，有问题请你自己改正吧。

### ISSUE THREAD

**Issue by xuiv** [c21xdx/lnmp13#3]
大佬，应你的要求我做了一个，经测试运行完美。
https://github.com/xuiv/v2ray-heroku

**Comment by xuiv** [comment]
今天看了一下bluemix.net，太难用了，IBM搞得乱七八糟的，go-buildpack只能用go 1.8.3，v2ray报错。

**Comment by c21xdx** [comment]
buildpack可以用第三方的，在那个yml里。就像IBM的官方例子一样，https://github.com/IBM-Cloud/go-hello-world/blob/master/manifest.yml

**Comment by xuiv** [comment]
我已经在bluemix布署成功了，要添加manifest.yml:
```
---
applications:
 - buildpack: https://github.com/cloudfoundry/go-buildpack.git
   env:
     GOVERSION: go1.10
     GOPACKAGENAME: github.com/xuiv/v2ray-heroku
```
我这里bluemix网速太差，我就不测试了，你自己弄吧
